# --- Main Colors ---
background            #141318
foreground            #e5e1e9
cursor                #e5e1e9
cursor_text_color     #141318

selection_background  #484459
selection_foreground  #e5dff9

url_color             #ecb8cd

# --- ANSI Colors ---
color0                #141318
color1                #ffb4ab
color2                #ecb8cd
color3                #c9c3dc
color4                #c8bfff
color5                #ecb8cd
color6                #c9c3dc
color7                #e5e1e9

color8                #48454e
color9                #93000a
color10               #613b4d
color11               #484459
color12               #473f77
color13               #484459
color14               #613b4d
color15               #c9c5d0

# --- Starship Prompt Bubbles ---
color255              #473f77
color254              #c8bfff
color253              #484459
color252              #c9c3dc
color251              #613b4d
color250              #ecb8cd
color249              #93000a
color248              #ffb4ab

color232              #e5deff
color233              #30285f
color234              #e5dff9
color235              #312e41
color236              #ffd8e7
color237              #482536
color238              #ffdad6
color239              #690005
color240              #e5deff

# Matched with unthemed light/dark
color243              #c8bfff
color244              #ffb4ab
color245              #48454e

# --- UI Elements ---
active_tab_foreground   #30285f
active_tab_background   #c8bfff
inactive_tab_foreground #e5deff
inactive_tab_background #473f77

active_border_color     #c8bfff
inactive_border_color   #938f99

# --- Marks ---
mark1_foreground        #1b1149
mark1_background        #e5deff
mark2_foreground        #1c192b
mark2_background        #e5dff9
mark3_foreground        #301121
mark3_background        #ffd8e7